---
title: "R Notebook"
output: html_document
---
```{r, eval = FALSE}
## ----setup, echo=FALSE, results="hide"----------------------------------------
knitr::opts_chunk$set(tidy = FALSE,
                      cache = FALSE,
                      dev = "png",
                      message = FALSE,
                      error = FALSE,
                      warning = TRUE)
```
1. load libraries

```{r}
library("ggplot2")
library("tidyverse")
library("ggrepel")
library("DESeq2")
library("pheatmap")
```
3. define paths
```{r}
local <- 0
prefix <- ifelse(local, "~", "")

results_dir <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/results")

dir_cervicalD <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/cervical_DESeq2/results/")
dir_cervicalM <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/cervical_MLSeq/results/")
dir_lungD <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/lung_DESeq2/results/")
dir_lungM <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/lung_MLSeq/results/")
dir_MAITD <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/MAIT_DESeq2/results/")
dir_MAITM <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/MAIT_MLSeq/results/")


```
4. load cervical data
```{r}
recompute <- 1
if(recompute){

  #results <- read.csv(file.path(dir_cervicalD, "07_results_cervical_all.csv"))
  results <- read_csv(file.path(dir_cervicalD, "07_results_cervical_all.csv")) %>%
          mutate("gene_name" = `...1`) %>%
          select(-`...1`)
  results %>% head()


  load(file.path(dir_cervicalM, "07_pam.rda"))
  load(file.path(dir_cervicalM, "08_plda.rda"))
  load(file.path(dir_cervicalM, "09_plda2.rda"))
  load(file.path(dir_cervicalM, "10_vnsc.rda"))

  pam <- tibble("gene_name" = genes.pam) %>%
          mutate("pam" = 1)
  plda <- tibble("gene_name" = genes.plda) %>%
          mutate("plda" = 1)
  plda2 <- tibble("gene_name" = genes.plda2) %>%
          mutate("plda2" = 1)
  vnsc <- tibble("gene_name" = genes.vnsc) %>%
          mutate("vnsc" = 1)

  mlseq <- full_join(pam, full_join(plda, full_join(plda2, vnsc)))

  deseq2_mlseq <- left_join(results, mlseq, by = "gene_name") %>%
          replace_na(list(pam = 0, plda = 0, plda2 = 0, vnsc = 0))

  #new column with information on number of classifiers that selected the gene
  deseq2_mlseq$mlseq <- deseq2_mlseq$pam + deseq2_mlseq$plda + deseq2_mlseq$plda2 + deseq2_mlseq$vnsc
  deseq2_mlseq$MLSeq <- as.factor(deseq2_mlseq$pam + deseq2_mlseq$plda + deseq2_mlseq$plda2 + deseq2_mlseq$vnsc)
  deseq2_mlseq$pam <- as.factor(deseq2_mlseq$pam)
  deseq2_mlseq$plda <- as.factor(deseq2_mlseq$plda)
  deseq2_mlseq$plda2 <- as.factor(deseq2_mlseq$plda2)
  deseq2_mlseq$vnsc <- as.factor(deseq2_mlseq$vnsc)

  #add log10 pvalue
  deseq2_mlseq$log10_pvalue <- -log10(deseq2_mlseq$pvalue)


}
```
heatmap cervical
```{r}


load( file= file.path(dir_cervicalD, "02b_rld.Rdata"))
rld
load( file= file.path(dir_cervicalD, "03_dds_pre_processed.Rdata"))
dds

dds <- estimateSizeFactors(dds)

#order by pvalue
select <- order(results$pvalue)[1:100]
genes <- results$gene_name[select]


mlseq_data <- deseq2_mlseq %>%
        filter(gene_name %in% row.names(assay(dds)[genes,])) %>%
        select(gene_name, log10_pvalue, pam, plda, plda2, vnsc)


row_anno_df <- data.frame(
        #mlseq_data$pvalue,
        #mlseq_data$log2FoldChange,
        mlseq_data$log10_pvalue,
        mlseq_data$pam,
        mlseq_data$plda,
        mlseq_data$plda2,
        mlseq_data$vnsc,
        row.names = mlseq_data$gene_name)
colnames(row_anno_df) <- c("-log10(p-value)", "NSC", "PLDA", "PLDA2", "vNSC")


ann_col <- list(
        vNSC= c("0" = "#f2f2f2", "1" = "blue"),
        PLDA2 = c("0" = "#f2f2f2", "1" = "red"),
        PLDA = c("0" = "#f2f2f2", "1" = "#4d390c"),
        NSC = c("0" = "#f2f2f2", "1" = "purple")
)

load(file =file.path(dir_cervicalD, "annotation"))

as <- assay(rld)[genes,]
pheatmap(as,
         cluster_rows = TRUE,
         show_rownames = TRUE,
         show_colnames = FALSE,
         cluster_cols = TRUE,
         border_color = NA,
         #height = 20,
         cellheight = 10,
         treeheight_col = 0,
         annotation_colors = ann_col,
         annotation_col = annotation,
         annotation_row = row_anno_df
)
```
5. plot cervical data

```{r}
if(recompute){




  ggplot(data=deseq2_mlseq, aes(x=log2FoldChange, y=-log10(pvalue), col=MLSeq)) +
          geom_point() +
          theme_minimal() +
          #geom_text_repel() +
          scale_color_manual(values=c( "orange", "red", "purple", "black")) +#keep colors constant - take out grey
          geom_vline(xintercept=c(-1, 1), col="red") +
          geom_hline(yintercept=-log10(0.05), col="red")

ggplot(data=deseq2_mlseq, aes(x=log2FoldChange, y=-log10(pvalue), col=pam)) +
          geom_point() +
          theme_minimal() +
          #geom_text_repel() +
          scale_color_manual(values=c( "grey", "orange", "red", "purple", "black")) +#keep colors constant - take out grey
          geom_vline(xintercept=c(-1, 1), col="red") +
          geom_hline(yintercept=-log10(0.05), col="red")

}
```
lung
```{r}
recompute <- 1
if(recompute){

  results <- read_csv(file.path(dir_lungD, "07_results_all.csv")) %>%
          mutate("gene_name" = `...1`) %>%
          select(-`...1`)
  results %>% head()
  results[1:39, 5] <- 2.23e-308

load(file.path(dir_lungM, "07_pam.rda"))
load(file.path(dir_lungM, "08_plda.rda"))
load(file.path(dir_lungM, "09_plda2.rda"))
load(file.path(dir_lungM, "10_vnsc.rda"))

  pam <- tibble("gene_name" = genes.pam) %>%
          mutate("pam" = 1)
  plda <- tibble("gene_name" = genes.plda) %>%
          mutate("plda" = 1)
  plda2 <- tibble("gene_name" = genes.plda2) %>%
          mutate("plda2" = 1)
  vnsc <- tibble("gene_name" = genes.vnsc) %>%
          mutate("vnsc" = 1)

  mlseq <- full_join(pam, full_join(plda, full_join(plda2, vnsc)))

  deseq2_mlseq <- left_join(results, mlseq, by = "gene_name") %>%
          replace_na(list(pam = 0, plda = 0, plda2 = 0, vnsc = 0))

  deseq2_mlseq$MLSeq <- as.factor(deseq2_mlseq$pam + deseq2_mlseq$plda + deseq2_mlseq$plda2 + deseq2_mlseq$vnsc)
  deseq2_mlseq$pam <- as.factor(deseq2_mlseq$pam)
  deseq2_mlseq$plda <- as.factor(deseq2_mlseq$plda)
  deseq2_mlseq$plda2 <- as.factor(deseq2_mlseq$plda2)
  deseq2_mlseq$vnsc <- as.factor(deseq2_mlseq$vnsc)



  save(deseq2_mlseq, file = file.path(results_dir, "lung_table.Rdata"))
} else{
  load(file = file.path(results_dir, "lung_table.Rdata"))
}
```
heatmap lung
```{r}
#new column with information on number of classifiers that selected the gene
#deseq2_mlseq$MLSeq <- deseq2_mlseq$pam + deseq2_mlseq$plda + deseq2_mlseq$plda2 + deseq2_mlseq$vnsc


#add log10 pvalue
deseq2_mlseq$log10_pvalue <- -log10(deseq2_mlseq$pvalue)

load( file= file.path(dir_lungD, "03_vsd.Rdata"))
#vsd
load( file= file.path(dir_lungD, "03_dds_pre_processed.Rdata"))
#dds

dds <- estimateSizeFactors(dds)

#order by pvalue
select <- order(results$pvalue)[1:100]
genes <- results$gene_name[select]


mlseq_data <- deseq2_mlseq %>%
        filter(gene_name %in% row.names(assay(dds)[genes,])) %>%
        select(gene_name, log10_pvalue, pam, plda, plda2, vnsc)


row_anno_df <- data.frame(
        #mlseq_data$pvalue,
        #mlseq_data$log2FoldChange,
        mlseq_data$log10_pvalue,
        mlseq_data$pam,
        mlseq_data$plda,
        mlseq_data$plda2,
        mlseq_data$vnsc,
        row.names = mlseq_data$gene_name)
colnames(row_anno_df) <- c("-log10(p-value)", "NSC", "PLDA", "PLDA2", "vNSC")


ann_col <- list(
        vNSC= c("0" = "#f2f2f2", "1" = "blue"),
        PLDA2 = c("0" = "#f2f2f2", "1" = "red"),
        PLDA = c("0" = "#f2f2f2", "1" = "#4d390c"),
        NSC = c("0" = "#f2f2f2", "1" = "purple")
)

as <- assay(vsd)[genes,]
pheatmap(as,
         cluster_rows = TRUE,
         show_rownames = TRUE,
         show_colnames = FALSE,
         cluster_cols = TRUE,
         border_color = NA,
         #height = 20,
         cellheight = 10,
         treeheight_col = 0,
         annotation_colors = ann_col,
         # annotation_col = df,
         annotation_row = row_anno_df
)
```


plot lung data

```{r}
recompute <- 1
if(recompute){



  ggplot(data=deseq2_mlseq, aes(x=log2FoldChange, y=-log10(pvalue), col=MLSeq)) +
          geom_point() +
          theme_minimal() +
          #geom_text_repel() +
          scale_color_manual(values=c("grey", "orange", "red", "purple", "black")) +
          geom_vline(xintercept=c(-1, 1), col="red") +
          geom_hline(yintercept=-log10(0.05), col="red")
}
recompute <- 0
if(recompute){

  ggplot(data=deseq2_mlseq, aes(x=MLSeq, y=-log10(pvalue))) +
          geom_point() +
          theme_minimal() +
          #geom_text_repel() +
          scale_color_manual(values=c("grey", "orange", "red", "purple")) +
          geom_vline(xintercept=c(-1, 1), col="red") +
          geom_hline(yintercept=-log10(0.05), col="red")
}
```

MAIT
```{r}
recompute <- 1
if(recompute){


  results <- read_csv(file.path(dir_MAITD, "09_results_all.csv")) %>%
          mutate("gene_name" = `...1`) %>%
          select(-`...1`)
  results %>% head()
  results[1, 5] <- 2.23e-308

  load(file.path(dir_MAITM, "07_pam.rda"))
  load(file.path(dir_MAITM, "08_plda.rda"))
  load(file.path(dir_MAITM, "09_plda2.rda"))
  load(file.path(dir_MAITM, "10_vnsc.rda"))


  pam <- tibble("gene_name" = genes.pam) %>%
          mutate("pam" = 1)
  plda <- tibble("gene_name" = genes.plda) %>%
          mutate("plda" = 1)
  plda2 <- tibble("gene_name" = genes.plda2) %>%
          mutate("plda2" = 1)
  vnsc <- tibble("gene_name" = genes.vnsc) %>%
          mutate("vnsc" = 1)

  mlseq <- full_join(pam, full_join(plda, full_join(plda2, vnsc)))

  deseq2_mlseq <- left_join(results, mlseq, by = "gene_name") %>%
          replace_na(list(pam = 0, plda = 0, plda2 = 0, vnsc = 0))

  #new column with information on number of classifiers that selected the gene
  deseq2_mlseq$mlseq <- deseq2_mlseq$pam + deseq2_mlseq$plda + deseq2_mlseq$plda2 + deseq2_mlseq$vnsc
  deseq2_mlseq$MLSeq <- as.factor(deseq2_mlseq$pam + deseq2_mlseq$plda + deseq2_mlseq$plda2 + deseq2_mlseq$vnsc)
  deseq2_mlseq$pam <- as.factor(deseq2_mlseq$pam)
  deseq2_mlseq$plda <- as.factor(deseq2_mlseq$plda)
  deseq2_mlseq$plda2 <- as.factor(deseq2_mlseq$plda2)
  deseq2_mlseq$vnsc <- as.factor(deseq2_mlseq$vnsc)

  #add log10 pvalue
  deseq2_mlseq$log10_pvalue <- -log10(deseq2_mlseq$pvalue)


}
```
heatmap MAIT
```{r}


load( file= file.path(dir_MAITD, "03_vsd_K12.Rdata"))
vsd <- vsd_K12
head(vsd)
load( file= file.path(dir_MAITD, "05_dds_pre_processed.Rdata"))
dds <- dds_K12
head(dds)

dds <- estimateSizeFactors(dds)

#order by pvalue
select <- order(results$pvalue)[1:100]
genes <- results$gene_name[select]


mlseq_data <- deseq2_mlseq %>%
        filter(gene_name %in% row.names(assay(dds)[genes,])) %>%
        select(gene_name, log10_pvalue, pam, plda, plda2, vnsc)


row_anno_df <- data.frame(
        #mlseq_data$pvalue,
        #mlseq_data$log2FoldChange,
        mlseq_data$log10_pvalue,
        mlseq_data$pam,
        mlseq_data$plda,
        mlseq_data$plda2,
        mlseq_data$vnsc,
        row.names = mlseq_data$gene_name)
colnames(row_anno_df) <- c("-log10(p-value)", "NSC", "PLDA", "PLDA2", "vNSC")


ann_col <- list(
        vNSC= c("0" = "#f2f2f2", "1" = "blue"),
        PLDA2 = c("0" = "#f2f2f2", "1" = "red"),
        PLDA = c("0" = "#f2f2f2", "1" = "#4d390c"),
        NSC = c("0" = "#f2f2f2", "1" = "purple"),
        treatment = c(treated = "red", control = "green")
)

load(file = file.path(dir_MAITD, "annotation"))

as <- assay(vsd)[genes,]
pheatmap(as,
         cluster_rows = TRUE,
         show_rownames = TRUE,
         show_colnames = FALSE,
         cluster_cols = TRUE,
         border_color = NA,
         #height = 1000,
         cellheight = 10,
         cellwidth = 10,
         treeheight_col = 0,
         annotation_colors = ann_col,
         annotation_col = annotation,
         annotation_row = row_anno_df
)
```
5. plot MAIT data

```{r}
if(recompute){




  ggplot(data=deseq2_mlseq, aes(x=log2FoldChange, y=-log10(pvalue), col=MLSeq)) +
          geom_point() +
          theme_minimal() +
          #geom_text_repel() +
          scale_color_manual(values=c( "orange", "red", "purple", "black")) +#keep colors constant - take out grey
          geom_vline(xintercept=c(-1, 1), col="red") +
          geom_hline(yintercept=-log10(0.05), col="red")

  ggplot(data=deseq2_mlseq, aes(x=log2FoldChange, y=-log10(pvalue), col=pam)) +
          geom_point() +
          theme_minimal() +
          #geom_text_repel() +
          scale_color_manual(values=c( "grey", "orange", "red", "purple", "black")) +#keep colors constant - take out grey
          geom_vline(xintercept=c(-1, 1), col="red") +
          geom_hline(yintercept=-log10(0.05), col="red")

}
```


