---
title: "R Notebook"
output: html_document
---
```{r, eval = FALSE}
## ----setup, echo=FALSE, results="hide"----------------------------------------
knitr::opts_chunk$set(tidy = FALSE,
                      cache = FALSE,
                      dev = "png",
                      message = FALSE,
                      error = FALSE,
                      warning = TRUE)
```
1. load libraries

```{r}
library("ggplot2")
library("tidyverse")
library("ggrepel")
```
3. read file of DESeq2 results
```{r}
local <- 0
prefix <- ifelse(local, "~", "")
dir_DESeq <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/cervical_DESeq2/results/")
dir_MLSeq <- file.path(prefix, "data/bioinf/projects/data/2022_MLseq_KP/cervical_MLSeq/results/")

results <- read.csv(file.path(dir_DESeq, "07_results_cervical_all.csv"))
results
```
4. include mlseq data
```{r}
load(file.path(dir_MLSeq, "07_pam.rda"))
load(file.path(dir_MLSeq, "08_plda.rda"))
load(file.path(dir_MLSeq, "09_plda2.rda"))
load(file.path(dir_MLSeq, "10_vnsc.rda"))

genes <- genes.pam
#create new column with 0
results$MLSeq <- 0
#iterate through all genes
for(gene in genes){

  #if genes.pam contains gene, set to 1
  pos <- which(results == gene)
  results[pos,8] <- results[pos,8] + 1
}
genes <- genes.plda
for(gene in genes){
  pos <- which(results == gene)
  results[pos,8] <- results[pos,8] + 1
}
genes <- genes.plda2

for(gene in genes){
  pos <- which(results == gene)
  results[pos,8] <- results[pos,8] + 1
}
genes <- genes.vnsc

for(gene in genes){
  pos <- which(results == gene)
  results[pos,8] <- results[pos,8] + 1
}

results$MLSeq <- as.factor(results$MLSeq)
```
5. plot

```{r}



ggplot(data=results, aes(x=log2FoldChange, y=-log10(pvalue), col=MLSeq)) +
  geom_point() +
  theme_minimal() +
  #geom_text_repel() +
  scale_color_manual(values=c("grey", "orange", "red", "purple")) +
  geom_vline(xintercept=c(-1, 1), col="red") +
  geom_hline(yintercept=-log10(0.05), col="red")
```
```{r}
ggplot(data=results, aes(x=MLSeq, y=-log10(pvalue))) +
        geom_point() +
        theme_minimal() +
        #geom_text_repel() +
        scale_color_manual(values=c("grey", "orange", "red", "purple")) +
        geom_vline(xintercept=c(-1, 1), col="red") +
        geom_hline(yintercept=-log10(0.05), col="red")
```


